import { Player } from '@/components/player'
import Sidebar from '@/components/sidebar'
import { PlayerProvider } from '@/provider/player-provider'
import '@mantine/carousel/styles.css'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

interface Children {
   children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Children>) {
   return (
      <html lang="en">
         <head>
            <ColorSchemeScript />
         </head>
         <body className={inter.className}>
            <MantineProvider>
               <PlayerProvider>
                  <div className="grid grid-cols-[auto,1fr] gap-4 p-4">
                     <Sidebar />
                     {children}
                  </div>
                  <Player />
               </PlayerProvider>
            </MantineProvider>
            <Toaster />
         </body>
      </html>
   )
}
